\LoadClass[a4paper,oneside,12pt]{book}

\RequirePackage{amsmath,amsfonts,amssymb,amsthm}
%To use equations

\RequirePackage[english,brazil]{babel}
\RequirePackage[nottoc,notlot,notlof]{tocbibind}
\RequirePackage{url}
\RequirePackage{hyperref}
\RequirePackage{graphicx}
\RequirePackage{setspace}
%%
%   Split tables in pages
%%
\RequirePackage{longtable}
%%
%   Change pages to landscape mode
%%
\RequirePackage{lscape}
%%
%   Ident the first line in the paragraph
%%
\RequirePackage{indentfirst}

%%
%   Defines Paper Geometry 
%%
\RequirePackage{geometry}
 \geometry{%margens
 a4paper,
 left=20mm,
 top=30mm,
 right=20mm,
 bottom=20mm
 }
 
%%
%   Defines Line Spacing
%%
\renewcommand{\baselinestretch}{1.5}

%%
%
%%
\pagestyle{plain}